# Generated by Django 6.1.1 on 2026-09-14 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('position', models.CharField(choices=[('PRESIDENT', 'President'), ('VP-INTERNAL', 'VP-Internal'), ('VP-EXTERNAL', 'VP-External'), ('SECRETARY', 'Secretary'), ('ASST. SECRETARY', 'Asst. Secretary'), ('TREASURER', 'Treasurer'), ('AUDITOR', 'Auditor'), ('ASST. AUDITOR', 'Asst. Auditor'), ('PROJECT MANAGER', 'Project Manager'), ('PRO', 'PRO'), ('ECO-WARRIOR', 'Eco-Warrior'), ('2ND YEAR REPRESENTATIVE', '2nd Year Representative')], max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('credentials', models.TextField(blank=True)),
                ('hierarchy_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['hierarchy_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OverallPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CandidatePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='core.candidate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
