# Generated by Django 6.1.1 on 2026-09-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
