# Generated by Django 6.1.1 on 2026-09-14 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_candidate_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='credentials',
        ),
        migrations.CreateModel(
            name='CandidateCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('ELEMENTARY', 'Elementary'), ('JUNIOR HIGH', 'Junior High School'), ('SENIOR HIGH', 'Senior High School'), ('COLLEGE', 'College'), ('GENERAL', 'General')], max_length=30)),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='core.candidate')),
            ],
            options={
                'ordering': ['education_level', 'order', 'id'],
            },
        ),
    ]
